### ISSUE TITLE
I can't connect this page to download pretrained data

### ISSUE THREAD

**Issue by jiho9702** [wtliao/layout2img#4]
See opts.py for the options. (You can download the pretrained models from [here](https://github.com/wtliao/layout2img/blob/main)
[here] is occured error : this is not the webpage you are looking for..
what should i do? help me

**Comment by wtliao** [comment]
> See opts.py for the options. (You can download the pretrained models from [here](https://github.com/wtliao/layout2img/blob/main) [here] is occured error : this is not the webpage you are looking for.. what should i do? help me

Please try https://1drv.ms/u/s!At2RxWvE6z1zgvEO2U1cvAL74id2Ng?e=gcmLuU this link.

**Comment by jiho9702** [comment]
thank you!!
